### ISSUE TITLE
OLE!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-EvaMarco#1]
Buen trabajo @EvaMarco  !

Tres cosicas para dejarlo fetén, fetén:

- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Indenta el código
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by EvaMarco** [comment]
Hello @oneeyedman I check all you tell me in the issue, and I have made all changes you asked me. I merged those changes into master. I couldn't make extras you told me but, I finish the zoom function I started the other day. Please tell me if everything its ok.

**Comment by oneeyedman** [comment]
Done!
